### ISSUE TITLE
encoding and decoding functions?

### ISSUE THREAD

**Issue by dcherian** [TomNicholas/pint-xarray#12]
It'd be nice to have a function that decodes `.attrs["units"]` when reading and encodes units in `.attrs["units"]` before writing.

E.g.

`ds.pint.decode()` yields xarray object with quantity arrays where possible

`ds.pint.encode()` will set the units attribute and convert to numpy arrays (or dask arrays?) so it can be serialized. `ds.pint.encode().to_netcdf(...)`

**Comment by keewis** [comment]
I think that's already available (although the code should probably be cleaned up), but instead of `decode` / `encode` it was named `quantify` / `dequantify`.

We should probably set up documentation to make this easier to find.

**Comment by dcherian** [comment]
hah. thanks!

**Comment by TomNicholas** [comment]
Yeah I chose quantify/dequantify to match pint, and to leave encode/decode for if we need some CF convention-specific functionality later.
